### ISSUE TITLE
error message occur when open aedt file with pyaedt version "0.6.22"

### ISSUE THREAD

**Issue by alien008** [pyansys/pyaedt#1911] opened 2022-11-01 02:56 UTC
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

i just install the newest version of pyaedt and start to run a simple code , the code could run but output some errors then proceed to run until finished. but the error message is wired.
here is  my code: "
    with Hfss(projectname="amf_GSG_SW_lumped_1000um.aedt", designname="HFSSDesign1", new_desktop_session=True,
              close_on_exit=True, student_version=False, specified_version="2022.1") as hfss:
        hfss.autosave_disable()
        objects = hfss.modeler.primitives.object_names
        print(objects)"
which is simple and no error occur before until i install the new pyaedt version
here is the output message:
      **Exception in thread pyaedt info: Logger Started
      pyaedt info: Launching PyAEDT outside AEDT with CPython and PythonNET.
      pyaedt info: AEDT installation Path C:\Program Files\AnsysEM\v221\Win64.
     ** _Thread-1:
      Traceback (most recent call last):
        File "C:\Users\zgl\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
          self.run()
        File "C:\Users\zgl\anaconda3\lib\threading.py", line 870, in run
          self._target(*self._args, **self._kwargs)
        File "C:\Users\zgl\anaconda3\lib\site-packages\pyaedt\application\Design.py", line 163, in load_aedt_thread
          settings._project_properties[path] = load_entire_aedt_file(path)
        File "C:\Users\zgl\anaconda3\lib\site-packages\pyaedt\generic\LoadAEDTFile.py", line 26, in load_entire_aedt_file
          return _load_entire_aedt_file(os.path.normpath(filename))
        File "C:\Users\zgl\anaconda3\lib\site-packages\pyaedt\generic\LoadAEDTFile.py", line 377, in _load_entire_aedt_file
          _read_aedt_file(filename)
        File "C:\Users\zgl\anaconda3\lib\site-packages\pyaedt\generic\LoadAEDTFile.py", line 347, in _read_aedt_file
          with open_file(filename, "rb") as aedt_fh:
      AttributeError: __enter__**
      pyaedt info: Launching AEDT with module PythonNET.
      pyaedt info: Ansoft.ElectronicsDesktop.2022.1 Started with process ID 4864.
      pyaedt info: Logger file C:\Users\zgl\Documents\Ansoft\pyaedt20221101_103621.log in use.
      pyaedt info: pyaedt v0.6.22
      pyaedt info: Python version 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
      pyaedt info: Project amf_GSG_SW_lumped_1000um has been opened.
      pyaedt info: Aedt Objects initialized
      pyaedt info: Variable Manager initialized
      pyaedt info: Design Loaded
      pyaedt info: Successfully loaded project materials !
      pyaedt info: Materials Loaded
      pyaedt info: aedt file load time 0.031244993209838867
      ['sub', 'box', 'cladding', 'air']

### Steps To Reproduce

just run the code :
with Hfss(projectname="amf_GSG_SW_lumped_1000um.aedt", designname="HFSSDesign1", new_desktop_session=True,
              close_on_exit=True, student_version=False, specified_version="2022.1") as hfss:
        hfss.autosave_disable()
        objects = hfss.modeler.primitives.object_names
        print(objects)"
the aedt file could be substitute by your own files

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

aiohttp==3.8.3
aiosignal==1.2.0
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client @ file:///C:/ci/anaconda-client_1635342752200/work
anaconda-navigator==2.1.1
anaconda-project @ file:///tmp/build/80754af9/anaconda-project_1637161053845/work
anyio @ file:///C:/ci/anyio_1620153418380/work/dist
appdirs==1.4.4
argh==0.26.2
argon2-cffi @ file:///C:/ci/argon2-cffi_1613037959010/work
arrow==0.13.1
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astroid @ file:///C:/ci/astroid_1628063293445/work
astropy @ file:///C:/ci/astropy_1638785655728/work
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
async-timeout==4.0.2
atomicwrites==1.4.0
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
autopep8 @ file:///opt/conda/conda-bld/autopep8_1639166893812/work
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1618170165463/work
backports.shutil-get-terminal-size @ file:///tmp/build/80754af9/backports.shutil_get_terminal_size_1608222128777/work
backports.tempfile @ file:///home/linux1/recipes/ci/backports.tempfile_1610991236607/work
backports.weakref==1.0.post1
bcrypt @ file:///C:/ci/bcrypt_1597936263757/work
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1631874778482/work
binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work
bitarray @ file:///C:/ci/bitarray_1641799256136/work
bkcharts==0.2
black==19.10b0
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
bokeh @ file:///C:/ci/bokeh_1638362940011/work
boto==2.49.0
Bottleneck==1.3.2
brotlipy==0.7.0
certifi==2021.10.8
cffi @ file:///C:/ci/cffi_1636542074879/work
chardet @ file:///C:/ci/chardet_1607690654534/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.0.3
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work
clr-loader==0.2.3
clyent==1.2.2
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
comtypes==1.1.10
conda==4.11.0
conda-build==3.21.7
conda-content-trust @ file:///tmp/build/80754af9/conda-content-trust_1617045594566/work
conda-pack @ file:///tmp/build/80754af9/conda-pack_1611163042455/work
conda-package-handling @ file:///C:/ci/conda-package-handling_1618262320430/work
conda-repo-cli @ file:///tmp/build/80754af9/conda-repo-cli_1620168426516/work
conda-token @ file:///tmp/build/80754af9/conda-token_1620076980546/work
conda-verify==3.4.2
contextlib2 @ file:///Users/ktietz/demo/mc3/conda-bld/contextlib2_1630668244042/work
cookiecutter @ file:///tmp/build/80754af9/cookiecutter_1617748928239/work
cryptography @ file:///C:/ci/cryptography_1633520552480/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
Cython @ file:///C:/ci/cython_1639474807736/work
cytoolz==0.11.0
daal4py==2021.4.0
dask==2021.10.0
debugpy @ file:///C:/ci/debugpy_1637073815078/work
decorator @ file:///tmp/build/80754af9/decorator_1632776554403/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
diff-match-patch @ file:///Users/ktietz/demo/mc3/conda-bld/diff-match-patch_1630511840874/work
distributed @ file:///C:/ci/distributed_1635968340418/work
docutils @ file:///C:/ci/docutils_1620828260973/work
entrypoints==0.3
et-xmlfile==1.1.0
fastcache==1.1.0
filelock @ file:///opt/conda/conda-bld/filelock_1642510437405/work
flake8 @ file:///tmp/build/80754af9/flake8_1620776156532/work
Flask @ file:///home/ktietz/src/ci/flask_1611932660458/work
fonttools==4.25.0
frozenlist==1.3.1
fsspec @ file:///opt/conda/conda-bld/fsspec_1642510437511/work
future==0.18.2
gevent @ file:///C:/ci/gevent_1628273793586/work
glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work
greenlet @ file:///C:/ci/greenlet_1628888262822/work
h5py==2.10.0
HeapDict @ file:///Users/ktietz/demo/mc3/conda-bld/heapdict_1630598515714/work
html5lib @ file:///Users/ktietz/demo/mc3/conda-bld/html5lib_1629144453894/work
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
imagecodecs @ file:///C:/ci/imagecodecs_1635529235632/work
imageio @ file:///tmp/build/80754af9/imageio_1617700267927/work
imagesize @ file:///tmp/build/80754af9/imagesize_1637939814114/work
importlib-metadata @ file:///C:/ci/importlib-metadata_1638543108096/work
inflection==0.5.1
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
intervaltree @ file:///Users/ktietz/demo/mc3/conda-bld/intervaltree_1630511889664/work
ipykernel @ file:///C:/ci/ipykernel_1633545574250/work/dist/ipykernel-6.4.1-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1635944310712/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work
isort @ file:///tmp/build/80754af9/isort_1628603791788/work
itsdangerous @ file:///tmp/build/80754af9/itsdangerous_1621432558163/work
jdcal @ file:///Users/ktietz/demo/mc3/conda-bld/jdcal_1630584345063/work
jedi @ file:///C:/ci/jedi_1611315808330/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
jinja2-time @ file:///tmp/build/80754af9/jinja2-time_1617751524098/work
joblib @ file:///tmp/build/80754af9/joblib_1635411271373/work
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonschema @ file:///Users/ktietz/demo/mc3/conda-bld/jsonschema_1630511932244/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1616770841739/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1616615302928/work
jupyter-core @ file:///C:/ci/jupyter_core_1636537213213/work
jupyter-server @ file:///C:/ci/jupyter_server_1616084298403/work
jupyterlab @ file:///tmp/build/80754af9/jupyterlab_1635799997693/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///opt/conda/conda-bld/jupyterlab_server_1641638588045/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
keyring @ file:///C:/ci/keyring_1638531661481/work
kiwisolver @ file:///C:/ci/kiwisolver_1612282606037/work
lazy-object-proxy @ file:///C:/ci/lazy-object-proxy_1616529307648/work
libarchive-c @ file:///tmp/build/80754af9/python-libarchive-c_1617780486945/work
llvmlite==0.37.0
locket==0.2.1
lxml @ file:///C:/ci/lxml_1640178400919/work
MarkupSafe==1.1.1
matlabengineforpython===R2021b
matplotlib @ file:///C:/ci/matplotlib-suite_1638289827560/work
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mccabe==0.6.1
menuinst @ file:///C:/ci/menuinst_1631733428175/work
mistune==0.8.4
mkl-fft==1.3.1
mkl-random @ file:///C:/ci/mkl_random_1626186184278/work
mkl-service==2.4.0
mock @ file:///tmp/build/80754af9/mock_1607622725907/work
more-itertools @ file:///tmp/build/80754af9/more-itertools_1637733554872/work
mpmath==1.2.1
msgpack @ file:///C:/ci/msgpack-python_1612287368835/work
multidict==4.7.6
multipledispatch==0.6.0
munkres==1.1.4
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbclassic @ file:///tmp/build/80754af9/nbclassic_1616085367084/work
nbclient @ file:///tmp/build/80754af9/nbclient_1614364831625/work
nbconvert @ file:///C:/ci/nbconvert_1624479163777/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx @ file:///tmp/build/80754af9/networkx_1633639043937/work
nltk==3.6.5
nose @ file:///opt/conda/conda-bld/nose_1642704612149/work
notebook @ file:///C:/ci/notebook_1637143794296/work
numba @ file:///C:/ci/numba_1635186101448/work
numexpr @ file:///C:/ci/numexpr_1640704408721/work
numpy @ file:///C:/ci/numpy_and_numpy_base_1626271903025/work
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
olefile @ file:///Users/ktietz/demo/mc3/conda-bld/olefile_1629805411829/work
openpyxl @ file:///tmp/build/80754af9/openpyxl_1632777717936/work
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas @ file:///C:/ci/pandas_1641443171711/work
pandocfilters @ file:///C:/ci/pandocfilters_1605102497129/work
paramiko @ file:///opt/conda/conda-bld/paramiko_1640109032755/work
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
partd @ file:///tmp/build/80754af9/partd_1618000087440/work
path @ file:///opt/conda/conda-bld/path_1641578212155/work
pathlib @ file:///E:/softwares/pathlib-1.0.1.tar.gz
pathlib2 @ file:///C:/ci/pathlib2_1625585790401/work
pathspec==0.7.0
patsy==0.5.2
pep8==1.7.1
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.4.0
pkginfo==1.7.1
pluggy @ file:///C:/ci/pluggy_1615976358795/work
plumbum==1.7.2
ply==3.11
poyo @ file:///tmp/build/80754af9/poyo_1617751526755/work
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1637050397234/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
psutil @ file:///C:/ci/psutil_1612298324802/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py @ file:///tmp/build/80754af9/py_1607971587848/work
pyaedt @ file:///D:/zgl/software/pyaedt-0.6.22.tar.gz
pycodestyle @ file:///tmp/build/80754af9/pycodestyle_1615748559966/work
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pycurl==7.44.1
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1621600989141/work
pyerfa @ file:///C:/ci/pyerfa_1621561004681/work
pyflakes @ file:///tmp/build/80754af9/pyflakes_1617200973297/work
Pygments @ file:///tmp/build/80754af9/pygments_1629234116488/work
PyJWT @ file:///C:/ci/pyjwt_1619651841937/work
pylint @ file:///C:/ci/pylint_1627536881874/work
pyls-spyder==0.4.0
PyNaCl @ file:///C:/ci/pynacl_1595000047588/work
pyodbc===4.0.0-unsupported
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1635333100036/work
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
pyreadline==2.1
pyrsistent @ file:///C:/ci/pyrsistent_1636111468851/work
PySocks @ file:///C:/ci/pysocks_1605287845585/work
pytest==6.2.4
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-lsp-black @ file:///tmp/build/80754af9/python-lsp-black_1634232156041/work
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.2.4
python-pptx @ file:///D:/%E5%AE%89%E8%A3%85%E5%8C%85/python-pptx-0.6.21%20%281%29.tar.gz
python-slugify @ file:///tmp/build/80754af9/python-slugify_1620405669636/work
pythonnet==3.0.0.post1
pytz @ file:///D:/%E5%AE%89%E8%A3%85%E5%8C%85/pytz-2022.1-py2.py3-none-any.whl
pyvista==0.36.1
PyWavelets @ file:///C:/ci/pywavelets_1601658407916/work
pywin32==304
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==6.0
pyzmq @ file:///C:/ci/pyzmq_1638435185959/work
QDarkStyle @ file:///tmp/build/80754af9/qdarkstyle_1617386714626/work
qstylizer @ file:///tmp/build/80754af9/qstylizer_1617713584600/work/dist/qstylizer-0.1.10-py2.py3-none-any.whl
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1637160816833/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1632739723211/work
QtPy @ file:///tmp/build/80754af9/qtpy_1629397026935/work
regex @ file:///C:/ci/regex_1629302316714/work
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
rope @ file:///tmp/build/80754af9/rope_1636994440010/work
rpyc==5.0.1
Rtree @ file:///C:/ci/rtree_1618421009405/work
ruamel-yaml-conda @ file:///C:/ci/ruamel_yaml_1616016967756/work
scikit-image==0.18.3
scikit-learn @ file:///C:/ci/scikit-learn_1642599125707/work
scikit-learn-intelex==2021.20211201.114757
scikit-rf @ file:///D:/%E5%AE%89%E8%A3%85%E5%8C%85/scikit-rf-0.23.1.zip
scipy @ file:///C:/ci/scipy_1641555198988/work
scooby==0.5.11
seaborn @ file:///tmp/build/80754af9/seaborn_1629307859561/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
simplegeneric==0.8.1
singledispatch @ file:///tmp/build/80754af9/singledispatch_1629321204894/work
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1623709665295/work
sniffio @ file:///C:/ci/sniffio_1614030707456/work
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1637937080595/work
sortedcollections @ file:///tmp/build/80754af9/sortedcollections_1611172717284/work
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1623949099177/work
soupsieve @ file:///tmp/build/80754af9/soupsieve_1636706018808/work
Sphinx==4.2.0
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///tmp/build/80754af9/sphinxcontrib-serializinghtml_1624451540180/work
sphinxcontrib-websupport @ file:///tmp/build/80754af9/sphinxcontrib-websupport_1597081412696/work
spyder @ file:///C:/ci/spyder_1636481183311/work
spyder-kernels @ file:///C:/ci/spyder-kernels_1634237040526/work
SQLAlchemy @ file:///C:/ci/sqlalchemy_1638290879826/work
statsmodels==0.12.2
sympy @ file:///C:/ci/sympy_1635237204453/work
tables==3.6.1
TBB==0.2
tblib @ file:///Users/ktietz/demo/mc3/conda-bld/tblib_1629402031467/work
terminado==0.9.4
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
text-unidecode @ file:///Users/ktietz/demo/mc3/conda-bld/text-unidecode_1629401354553/work
textdistance @ file:///tmp/build/80754af9/textdistance_1612461398012/work
threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work
tifffile @ file:///tmp/build/80754af9/tifffile_1627275862826/work
tinycss @ file:///tmp/build/80754af9/tinycss_1617713798712/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
toolz @ file:///tmp/build/80754af9/toolz_1636545406491/work
tornado @ file:///C:/ci/tornado_1606942392901/work
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work
typed-ast @ file:///C:/ci/typed-ast_1624953785070/work
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
ujson @ file:///C:/ci/ujson_1611241570789/work
unicodecsv==0.14.1
Unidecode @ file:///tmp/build/80754af9/unidecode_1614712377438/work
urllib3==1.26.7
vtk==9.1.0
watchdog @ file:///C:/ci/watchdog_1638349261759/work
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
Werkzeug @ file:///tmp/build/80754af9/werkzeug_1635505089296/work
whichcraft @ file:///tmp/build/80754af9/whichcraft_1617751293875/work
widgetsnbextension==3.5.1
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306167264/work
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.12.1
wslink==1.3.1
xlrd @ file:///tmp/build/80754af9/xlrd_1608072521494/work
XlsxWriter @ file:///tmp/build/80754af9/xlsxwriter_1636633762820/work
xlwings==0.24.9
xlwt==1.3.0
xmltodict @ file:///Users/ktietz/demo/mc3/conda-bld/xmltodict_1629301980723/work
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
yarl==1.7.2
zict==2.0.0
zipp @ file:///opt/conda/conda-bld/zipp_1641824620731/work
zope.event==4.5.0
zope.interface @ file:///C:/ci/zope.interface_1625036260333/work

**Comment by gmalinve** [comment] 2022-11-02 15:01
Hi @alien008 ,
We have tested it but couldn't reproduce your bug.
This is a pyaedt core feature and being extensively used it has seldom given back any exception. 
Maybe could you share your aedt file so we can properly test and see whether it's a pyaedt or a file issue?

**Comment by alien008** [comment] 2022-11-14 01:53
Hi,gmalinve,
Sorry for replying so late, i tested one again, even reinstalled anaconda. but there is still the message.
the attachment  contain the .py file and aedt file.
Thank you for your help!
[amf_GSG_SW_lumped_1000um.zip](https://github.com/pyansys/pyaedt/files/9998874/amf_GSG_SW_lumped_1000um.zip)

**Comment by alien008** [comment] 2022-11-14 08:24
Yes, i have updated to version 0.6.26, but the error message still occurs, Thank you!

**Comment by alien008** [comment] 2022-11-14 08:27
![179a4b52b50f754091aa3406c7d77a5](https://user-images.githubusercontent.com/53729221/201611383-871fb37c-c395-4946-986d-84b26c8cf947.png)
 this is the pycharm output,thanks!

**Comment by gmalinve** [comment] 2022-11-14 16:12
Hi @alien008 ,

I tested your file with both versions 22.1 and 22.2 and didn't get any issue.
Have you checked that you don't have the .lock file in your folder? because this will prevent the opening of the aedt file.

**Comment by alien008** [comment] 2022-11-16 09:36
Hi,gmalinve,
well, i think it's not because of the .lock file. I know that the .lock file will cause the aedt file to fail to open, but there is no .lock file under my folder, and the aedt file can be opened by python, and pycharm will output such an error, But the aedt file will execute normally. If I run the same file under pyaedt 0.4.23, no error will be reported. I do not know why either. Thank you!

**Comment by alien008** [comment] 2022-11-16 09:48
![842bf31e57b1e1c694aaf707937463e](https://user-images.githubusercontent.com/53729221/202146974-229c2fbd-3cbc-40b3-92d1-44bb07a6b93d.png)

**Comment by gmalinve** [comment] 2022-11-22 07:54
Hi @alien008 , yes at the moment we are investigating/fixing this case. A PR has been open to tackle it.

**Comment by MaxJPRey** [comment] 2022-11-23 08:58
Hi @alien008
This should be fixed within the last release 0.6.28 published yesterday.
Let us know if you still experiment any issues.
Thanks for your feedback and all the details you provided.

**Closed** 2022-12-02 13:19 UTC
Labels: bug
